# Generated by Django 5.1.7 on 2025-03-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myopensoft', '0003_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='EMP0000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('unpaid', 'Unpaid Leave'), ('annual', 'Annual Leave')], default='casual', max_length=20),
        ),
    ]
