# Generated by Django 5.1.7 on 2025-03-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myopensoft', '0005_remove_award_awarded_date_award_reward_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='award_name',
            field=models.CharField(choices=[('Innovation Award', 'Innovation Award'), ('Leadership Excellence', 'Leadership Excellence'), ('best team player', 'best team player'), ('Star performer', 'Star Performer')], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Unpaid Leave', 'Unpaid Leave'), ('Annual Leave', 'Annual Leave')], default='casual', max_length=20),
        ),
    ]
