# Generated by Django 5.1.7 on 2025-03-23 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myopensoft', '0008_alter_award_award_name_alter_leave_leave_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_rating', models.IntegerField()),
                ('manager_feedback', models.CharField(choices=[('Meets Expectations', 'Meets Expectations'), ('Exceeds Expectations', 'Exceeds Expectations'), ('Needs Improvement', 'Needs Improvement')], max_length=50)),
                ('promotion_consideration', models.BooleanField()),
                ('review_period', models.CharField(choices=[('Annual 2023', 'Annual 2023'), ('H2 2023', 'H2 2023'), ('H1 2023', 'H1 2023')])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_performance', to='myopensoft.employee')),
            ],
        ),
    ]
