# Generated by Django 5.1.7 on 2025-03-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myopensoft', '0010_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_performance',
            name='review_period',
            field=models.CharField(choices=[('Annual 2023', 'Annual 2023'), ('H2 2023', 'H2 2023'), ('H1 2023', 'H1 2023')], max_length=50),
        ),
    ]
